package com.cuong.ome.risk;

public enum RejectReason {
    INVALID_MESSAGE,
    UNKNOWN_SYMBOL,
    QUANTITY_EXCEEDS_MAX,
    QUANTITY_NON_POSITIVE,
    PRICE_NON_POSITIVE,
    PRICE_OUTSIDE_BAND,
    MARKET_ORDER_HAS_PRICE,
    LIMIT_ORDER_NO_PRICE,
    CLIENT_ORDER_ID_TOO_LONG,
    DUPLICATE_CLIENT_ORDER_ID,
    ORDER_NOT_FOUND,
    ORDER_NOT_CANCELLABLE,
    NO_LIQUIDITY
}
